INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `address_id`) 
VALUES (1, 'nombre1', 'apellido1', '1111-1111', '1970-01-01', '1', 0, now(), 1,'1@gmail.com', 1);
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (2, 'nombre2', 'apellido2', '1111-1112', '1970-01-02', '1', 0, now(), 1,'2@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (3, 'nombre3', 'apellido3', '1111-1113', '1970-01-03', '1', 0, now(), 1,'1@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (4, 'nombre4', 'apellido4', '1111-1114', '1970-01-04', '1', 0, now(), 1,'2@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (5, 'nombre5', 'apellido5', '1111-1115', '1970-01-05', '1', 0, now(), 1,'1@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (6, 'nombre6', 'apellido6', '1111-1116', '1970-01-06', '1', 0, now(), 1,'2@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (7, 'nombre7', 'apellido7', '1111-1117', '1970-01-07', '1', 0, now(), 1,'1@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (8, 'nombre8', 'apellido8', '1111-1118', '1970-01-08', '1', 0, now(), 1,'2@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (9, 'nombre9', 'apellido9', '1111-1119', '1970-01-09', '1', 0, now(), 1,'1@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (10, 'nombre10', 'apellido10', '1111-1120', '1970-01-10', '1', 0, now(), 1,'2@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (11, 'nombre11', 'apellido11', '1111-1121', '1970-01-11', '1', 0, now(), 1,'1@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (12, 'nombre12', 'apellido12', '1111-1122', '1970-01-12', '1', 0, now(), 1,'2@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (13, 'nombre13', 'apellido13', '1111-1123', '1970-01-13', '1', 0, now(), 1,'1@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (14, 'nombre14', 'apellido14', '1111-1124', '1970-01-14', '1', 0, now(), 1,'2@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (15, 'nombre15', 'apellido15', '1111-1125', '1970-01-15', '1', 0, now(), 1,'1@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (16, 'nombre16', 'apellido16', '1111-1126', '1970-01-16', '1', 0, now(), 1,'2@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (17, 'nombre17', 'apellido17', '1111-1127', '1970-01-17', '1', 0, now(), 1,'1@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (18, 'nombre18', 'apellido18', '1111-1128', '1970-01-18', '1', 0, now(), 1,'2@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (19, 'nombre19', 'apellido19', '1111-1129', '1970-01-19', '1', 0, now(), 1,'1@gmail.com','CR');
INSERT INTO `paymentassistant`.`pay_user` (`user_id`,`name`,`last_name`,`phone`,`birth`,`password`,`delete`,`last_update`, `active`, `email`, `region`) VALUES (20, 'nombre20', 'apellido20', '1111-1130', '1970-01-20', '1', 0, now(), 1,'2@gmail.com','CR');

